[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "pip install --break-system-packages --upgrade pip",
    "pip install --break-system-packages --no-cache-dir -r requirements.txt"
]
