[phases.setup]
aptPkgs = ["build-essential", "curl"]

[phases.install]
cmds = ["pip install -r requirements_minimal.txt"]

[start]
cmds = ["/app/entrypoint.sh"]

[variables]
PYTHON_VERSION = "3.10"

[nixpacks]
start-command = "/app/entrypoint.sh"
