[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "/app/entrypoint.sh"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = { europe-west4-drams3a = { numReplicas = 1 } }
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
