[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[environments.production]
[environments.production.variables]
# AI API Keys (configure in Railway dashboard for security)
# OPENAI_API_KEY = "your-openai-api-key"
# SERPER_API_KEY = "your-serper-api-key"

# Morvo API Security
# MORVO_API_KEY = "your-secure-morvo-api-key"

# Supabase Configuration
# SUPABASE_URL = "your-supabase-project-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-supabase-service-role-key"

# Social Media APIs
# FACEBOOK_ACCESS_TOKEN = "your-facebook-access-token"
# TWITTER_BEARER_TOKEN = "your-twitter-bearer-token"
# LINKEDIN_ACCESS_TOKEN = "your-linkedin-access-token"
# YOUTUBE_API_KEY = "your-youtube-api-key"

# Analytics APIs
# GOOGLE_ANALYTICS_CREDENTIALS = "base64-encoded-credentials"
# GOOGLE_ADS_DEVELOPER_TOKEN = "your-google-ads-token"

# Business Intelligence APIs
# SEMRUSH_API_KEY = "your-semrush-api-key"
# AHREFS_API_KEY = "your-ahrefs-api-key"
# SIMILARWEB_API_KEY = "your-similarweb-api-key"

# Automation APIs
# ZAPIER_WEBHOOK_URL = "your-zapier-webhook-url"
# MAKE_WEBHOOK_URL = "your-make-webhook-url"

# MCP Configuration
# MCP_SERVER_URL = "your-mcp-server-url"
# MCP_API_KEY = "your-mcp-api-key"

# Application Configuration
PORT = "8000"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "info"
