[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "uvicorn test_minimal_api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
