[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "uvicorn morvo_api_railway:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 100
